# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apps.Gov
email: andrew.stroup@pif.gov
description: > # this means to ignore newlines until "baseurl:"
  A marketplace to find cloud based products to help the government 
  operate better.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://apps.pif.gov" # the base hostname & protocol for your site
twitter_username: appsgov
github_username:  presidential-innovation-fellows
repo_url: https://github.com/presidential-innovation-fellows/apps-gov

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

page_gen:
  - data: products
    template: page
    name: url
    dir: products
