# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apps.Gov
email: andrew.stroup@pif.gov
description: > # this means to ignore newlines until "baseurl:"
  A marketplace to find cloud-based products to help the government
  operate better.
url: "https://apps.gov" # the base hostname & protocol for your site
twitter_username: innovfellows
github_username:  presidential-innovation-fellows
repo_url: https://github.com/presidential-innovation-fellows/apps-gov

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- node_modules
- package.json
- vendor
- system-security-plan.yml
- about.yml
- manifest.yml

page_gen:
  - data: apps
    template: page
    name: url
    dir: apps

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:

  # If defined and browserify and uglifyify are installed, the plugin will
  # generate a bundle to define the renderJekyllPagesApiSearchResults
  # function.
  browserify:
    source: 'assets/js/products.js'
    target: 'assets/js/products-bundle.js'
